--------------------------------------------------------------------
-- NEURO-SYNC - SCRIPT DE CRIAÇÃO DE TABELAS
--------------------------------------------------------------------

--------------------------------------------------------------------
-- TABELA: EMPRESA
--------------------------------------------------------------------
CREATE TABLE EMPRESA (
    ID_EMPRESA           NUMBER(10)      NOT NULL,
    RAZAO_SOCIAL         VARCHAR2(150)   NOT NULL,
    NOME_FANTASIA        VARCHAR2(150),
    CNPJ                 VARCHAR2(20)    NOT NULL,
    EMAIL_CORPORATIVO    VARCHAR2(150),
    TELEFONE_CORPORATIVO VARCHAR2(20),
    DATA_CADASTRO        DATE            DEFAULT SYSDATE NOT NULL,
    STATUS_ATIVO         CHAR(1)         DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_EMPRESA PRIMARY KEY (ID_EMPRESA),
    CONSTRAINT UQ_EMPRESA_CNPJ UNIQUE (CNPJ),
    CONSTRAINT CK_EMPRESA_STATUS_ATIVO CHECK (STATUS_ATIVO IN ('S','N'))
);

--------------------------------------------------------------------
-- TABELA: FILIAL
--------------------------------------------------------------------
CREATE TABLE FILIAL (
    ID_FILIAL        NUMBER(10)      NOT NULL,
    ID_EMPRESA       NUMBER(10)      NOT NULL,
    NOME_FILIAL      VARCHAR2(150)   NOT NULL,
    CODIGO_FILIAL    VARCHAR2(30),
    CIDADE           VARCHAR2(100),
    UF               VARCHAR2(2),
    PAIS             VARCHAR2(50),
    ENDERECO         VARCHAR2(255),
    DATA_CADASTRO    DATE            DEFAULT SYSDATE NOT NULL,
    STATUS_ATIVO     CHAR(1)         DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_FILIAL PRIMARY KEY (ID_FILIAL),
    CONSTRAINT FK_FILIAL_EMPRESA FOREIGN KEY (ID_EMPRESA)
        REFERENCES EMPRESA (ID_EMPRESA),
    CONSTRAINT CK_FILIAL_STATUS_ATIVO CHECK (STATUS_ATIVO IN ('S','N'))
);

--------------------------------------------------------------------
-- TABELA: SETOR
--------------------------------------------------------------------
CREATE TABLE SETOR (
    ID_SETOR       NUMBER(10)      NOT NULL,
    ID_FILIAL      NUMBER(10)      NOT NULL,
    NOME_SETOR     VARCHAR2(150)   NOT NULL,
    CODIGO_SETOR   VARCHAR2(30),
    ANDAR          VARCHAR2(20),
    DESCRICAO      VARCHAR2(255),
    DATA_CADASTRO  DATE            DEFAULT SYSDATE NOT NULL,
    STATUS_ATIVO   CHAR(1)         DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_SETOR PRIMARY KEY (ID_SETOR),
    CONSTRAINT FK_SETOR_FILIAL FOREIGN KEY (ID_FILIAL)
        REFERENCES FILIAL (ID_FILIAL),
    CONSTRAINT CK_SETOR_STATUS_ATIVO CHECK (STATUS_ATIVO IN ('S','N'))
);

--------------------------------------------------------------------
-- TABELA: PERFIL
--------------------------------------------------------------------
CREATE TABLE PERFIL (
    ID_PERFIL      NUMBER(10)      NOT NULL,
    NOME_PERFIL    VARCHAR2(50)    NOT NULL,
    DESCRICAO      VARCHAR2(255),
    NIVEL_ACESSO   NUMBER(2),
    STATUS_ATIVO   CHAR(1)         DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_PERFIL PRIMARY KEY (ID_PERFIL),
    CONSTRAINT UQ_PERFIL_NOME UNIQUE (NOME_PERFIL),
    CONSTRAINT CK_PERFIL_STATUS_ATIVO CHECK (STATUS_ATIVO IN ('S','N'))
);

--------------------------------------------------------------------
-- TABELA: USUARIO
--------------------------------------------------------------------
CREATE TABLE USUARIO (
    ID_USUARIO           NUMBER(10)      NOT NULL,
    ID_SETOR             NUMBER(10)      NOT NULL,
    NOME_COMPLETO        VARCHAR2(150)   NOT NULL,
    EMAIL_CORPORATIVO    VARCHAR2(150)   NOT NULL,
    MATRICULA_INTERNA    VARCHAR2(50),
    TELEFONE             VARCHAR2(20),
    DATA_ADMISSAO        DATE,
    DATA_CADASTRO        DATE            DEFAULT SYSDATE NOT NULL,
    STATUS_ATIVO         CHAR(1)         DEFAULT 'S' NOT NULL,
    FLAG_NEURODIVERGENTE CHAR(1)         DEFAULT 'N' NOT NULL,
    OBSERVACOES_SUPORTE  VARCHAR2(500),
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIO_SETOR FOREIGN KEY (ID_SETOR)
        REFERENCES SETOR (ID_SETOR),
    CONSTRAINT UQ_USUARIO_EMAIL UNIQUE (EMAIL_CORPORATIVO),
    CONSTRAINT CK_USUARIO_STATUS_ATIVO CHECK (STATUS_ATIVO IN ('S','N')),
    CONSTRAINT CK_USUARIO_NEURODIVERGENTE CHECK (FLAG_NEURODIVERGENTE IN ('S','N'))
    SENHA_HASH             VARCHAR2(255) NOT NULL,
    DATA_ULTIMO_LOGIN      DATE,
    QTDE_TENTATIVAS_LOGIN  NUMBER(3) DEFAULT 0 NOT NULL,
    MUDAR_SENHA_PROX_LOGIN CHAR(1) DEFAULT 'N' NOT NULL
        CHECK (MUDAR_SENHA_PROX_LOGIN IN ('S','N')
);

--------------------------------------------------------------------
-- TABELA: USUARIO_PERFIL (associação N:N entre USUARIO e PERFIL)
--------------------------------------------------------------------
CREATE TABLE USUARIO_PERFIL (
    ID_USUARIO_PERFIL   NUMBER(10)   NOT NULL,
    ID_USUARIO          NUMBER(10)   NOT NULL,
    ID_PERFIL           NUMBER(10)   NOT NULL,
    DATA_ATRIBUICAO     DATE         DEFAULT SYSDATE NOT NULL,
    USUARIO_RESPONSAVEL VARCHAR2(150),
    STATUS_ATIVO        CHAR(1)      DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_USUARIO_PERFIL PRIMARY KEY (ID_USUARIO_PERFIL),
    CONSTRAINT FK_USUARIO_PERFIL_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_USUARIO_PERFIL_PERFIL FOREIGN KEY (ID_PERFIL)
        REFERENCES PERFIL (ID_PERFIL),
    CONSTRAINT CK_USUARIO_PERFIL_STATUS_ATIVO CHECK (STATUS_ATIVO IN ('S','N'))
);

--------------------------------------------------------------------
-- TABELA: PREFERENCIA_SENSORIAL
--------------------------------------------------------------------
CREATE TABLE PREFERENCIA_SENSORIAL (
    ID_PREFERENCIA          NUMBER(10)     NOT NULL,
    ID_USUARIO              NUMBER(10)     NOT NULL,
    RUIDO_MAX_DB            NUMBER(5,2),
    LUZ_MIN_LUX             NUMBER(7,2),
    LUZ_MAX_LUX             NUMBER(7,2),
    TOLERANCIA_VISUAL       NUMBER(2),
    PREFERE_ZONA            VARCHAR2(30),
    OBSERVACOES_PREFERENCIA VARCHAR2(500),
    DATA_INICIO_VIGENCIA    DATE           NOT NULL,
    DATA_FIM_VIGENCIA       DATE,
    ATIVO                   CHAR(1)        DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_PREFERENCIA_SENSORIAL PRIMARY KEY (ID_PREFERENCIA),
    CONSTRAINT FK_PREF_SENSORIAL_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT CK_PREF_SENSORIAL_ATIVO CHECK (ATIVO IN ('S','N'))
);

--------------------------------------------------------------------
-- TABELA: ZONA_SENSORIAL
--------------------------------------------------------------------
CREATE TABLE ZONA_SENSORIAL (
    ID_ZONA                  NUMBER(10)    NOT NULL,
    ID_FILIAL                NUMBER(10)    NOT NULL,
    NOME_ZONA                VARCHAR2(150) NOT NULL,
    TIPO_ZONA                VARCHAR2(50),
    DESCRICAO                VARCHAR2(255),
    RUIDO_MEDIO_ESTIMADO_DB  NUMBER(5,2),
    LUZ_MEDIA_ESTIMADO_LUX   NUMBER(7,2),
    CARACTERISTICA_VISUAL    VARCHAR2(50),
    CAPACIDADE_ESTIMADA      NUMBER(5),
    STATUS_ATIVO             CHAR(1)       DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_ZONA_SENSORIAL PRIMARY KEY (ID_ZONA),
    CONSTRAINT FK_ZONA_FILIAL FOREIGN KEY (ID_FILIAL)
        REFERENCES FILIAL (ID_FILIAL),
    CONSTRAINT CK_ZONA_STATUS_ATIVO CHECK (STATUS_ATIVO IN ('S','N'))
);

--------------------------------------------------------------------
-- TABELA: ESTACAO_TRABALHO
--------------------------------------------------------------------
CREATE TABLE ESTACAO_TRABALHO (
    ID_ESTACAO             NUMBER(10)    NOT NULL,
    ID_ZONA                NUMBER(10)    NOT NULL,
    CODIGO_ESTACAO         VARCHAR2(50)  NOT NULL,
    DESCRICAO              VARCHAR2(255),
    PERMITE_RESERVA        CHAR(1)       DEFAULT 'S' NOT NULL,
    PERMITE_USO_ESPONTANEO CHAR(1)       DEFAULT 'S' NOT NULL,
    STATUS_ESTACAO         VARCHAR2(20)  DEFAULT 'ATIVA' NOT NULL,
    OBSERVACOES            VARCHAR2(500),
    DATA_CADASTRO          DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ESTACAO_TRABALHO PRIMARY KEY (ID_ESTACAO),
    CONSTRAINT FK_ESTACAO_ZONA FOREIGN KEY (ID_ZONA)
        REFERENCES ZONA_SENSORIAL (ID_ZONA),
    CONSTRAINT UQ_ESTACAO_CODIGO UNIQUE (CODIGO_ESTACAO),
    CONSTRAINT CK_ESTACAO_PERMITE_RESERVA CHECK (PERMITE_RESERVA IN ('S','N')),
    CONSTRAINT CK_ESTACAO_PERMITE_USO_ESP CHECK (PERMITE_USO_ESPONTANEO IN ('S','N')),
    CONSTRAINT CK_ESTACAO_STATUS CHECK (STATUS_ESTACAO IN ('ATIVA','EM_MANUTENCAO','INATIVA'))
);

--------------------------------------------------------------------
-- TABELA: TIPO_SENSOR
--------------------------------------------------------------------
CREATE TABLE TIPO_SENSOR (
    ID_TIPO_SENSOR  NUMBER(10)    NOT NULL,
    NOME_TIPO_SENSOR VARCHAR2(50) NOT NULL,
    UNIDADE_MEDIDA   VARCHAR2(20),
    DESCRICAO        VARCHAR2(255),
    STATUS_ATIVO     CHAR(1)      DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_TIPO_SENSOR PRIMARY KEY (ID_TIPO_SENSOR),
    CONSTRAINT UQ_TIPO_SENSOR_NOME UNIQUE (NOME_TIPO_SENSOR),
    CONSTRAINT CK_TIPO_SENSOR_STATUS_ATIVO CHECK (STATUS_ATIVO IN ('S','N'))
);

--------------------------------------------------------------------
-- TABELA: SENSOR
--------------------------------------------------------------------
CREATE TABLE SENSOR (
    ID_SENSOR             NUMBER(10)    NOT NULL,
    ID_ESTACAO            NUMBER(10)    NOT NULL,
    ID_TIPO_SENSOR        NUMBER(10)    NOT NULL,
    IDENTIFICADOR_HARDWARE VARCHAR2(100) NOT NULL,
    DATA_INSTALACAO       DATE,
    DATA_ULTIMA_MANUTENCAO DATE,
    STATUS_SENSOR         VARCHAR2(20)  DEFAULT 'ATIVO' NOT NULL,
    OBSERVACOES           VARCHAR2(500),
    CONSTRAINT PK_SENSOR PRIMARY KEY (ID_SENSOR),
    CONSTRAINT FK_SENSOR_ESTACAO FOREIGN KEY (ID_ESTACAO)
        REFERENCES ESTACAO_TRABALHO (ID_ESTACAO),
    CONSTRAINT FK_SENSOR_TIPO_SENSOR FOREIGN KEY (ID_TIPO_SENSOR)
        REFERENCES TIPO_SENSOR (ID_TIPO_SENSOR),
    CONSTRAINT UQ_SENSOR_IDENTIFICADOR UNIQUE (IDENTIFICADOR_HARDWARE),
    CONSTRAINT CK_SENSOR_STATUS CHECK (STATUS_SENSOR IN ('ATIVO','EM_MANUTENCAO','DESATIVADO'))
);

--------------------------------------------------------------------
-- TABELA: LEITURA_SENSOR
--------------------------------------------------------------------
CREATE TABLE LEITURA_SENSOR (
    ID_LEITURA        NUMBER(10)   NOT NULL,
    ID_SENSOR         NUMBER(10)   NOT NULL,
    DATA_HORA_LEITURA DATE         NOT NULL,
    VALOR_MEDIDO      NUMBER(10,2) NOT NULL,
    QUALIDADE_SINAL   NUMBER(3),
    ORIGEM_REGISTRO   VARCHAR2(20),
    DATA_PROCESSAMENTO DATE        DEFAULT SYSDATE,
    CONSTRAINT PK_LEITURA_SENSOR PRIMARY KEY (ID_LEITURA),
    CONSTRAINT FK_LEITURA_SENSOR_SENSOR FOREIGN KEY (ID_SENSOR)
        REFERENCES SENSOR (ID_SENSOR),
    CONSTRAINT CK_LEITURA_QUALIDADE CHECK (QUALIDADE_SINAL BETWEEN 0 AND 100)
);

--------------------------------------------------------------------
-- TABELA: STATUS_RESERVA
--------------------------------------------------------------------
CREATE TABLE STATUS_RESERVA (
    ID_STATUS_RESERVA NUMBER(10)    NOT NULL,
    CODIGO_STATUS     VARCHAR2(30)  NOT NULL,
    DESCRICAO         VARCHAR2(255),
    E_FINALIZADOR     CHAR(1)       DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_STATUS_RESERVA PRIMARY KEY (ID_STATUS_RESERVA),
    CONSTRAINT UQ_STATUS_RESERVA_CODIGO UNIQUE (CODIGO_STATUS),
    CONSTRAINT CK_STATUS_RESERVA_FINALIZADOR CHECK (E_FINALIZADOR IN ('S','N'))
);

--------------------------------------------------------------------
-- TABELA: RESERVA_ESTACAO
--------------------------------------------------------------------
CREATE TABLE RESERVA_ESTACAO (
    ID_RESERVA                NUMBER(10)   NOT NULL,
    ID_USUARIO                NUMBER(10)   NOT NULL,
    ID_ESTACAO                NUMBER(10)   NOT NULL,
    ID_STATUS_RESERVA         NUMBER(10)   NOT NULL,
    DATA_HORA_SOLICITACAO     DATE         DEFAULT SYSDATE NOT NULL,
    DATA_HORA_INICIO_PREVISTA DATE         NOT NULL,
    DATA_HORA_FIM_PREVISTA    DATE         NOT NULL,
    DATA_HORA_CHECKIN         DATE,
    DATA_HORA_CHECKOUT        DATE,
    ORIGEM_RESERVA            VARCHAR2(20),
    MOTIVO_CANCELAMENTO       VARCHAR2(255),
    INDICE_CONFORTO_CALCULADO NUMBER(5,2),
    OBSERVACOES               VARCHAR2(500),
    CONSTRAINT PK_RESERVA_ESTACAO PRIMARY KEY (ID_RESERVA),
    CONSTRAINT FK_RESERVA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_RESERVA_ESTACAO FOREIGN KEY (ID_ESTACAO)
        REFERENCES ESTACAO_TRABALHO (ID_ESTACAO),
    CONSTRAINT FK_RESERVA_STATUS FOREIGN KEY (ID_STATUS_RESERVA)
        REFERENCES STATUS_RESERVA (ID_STATUS_RESERVA)
);

--------------------------------------------------------------------
-- TABELA: AVALIACAO_ESTACAO
--------------------------------------------------------------------
CREATE TABLE AVALIACAO_ESTACAO (
    ID_AVALIACAO          NUMBER(10)   NOT NULL,
    ID_RESERVA            NUMBER(10)   NOT NULL,
    NOTA_CONFORTO_GERAL   NUMBER(1)    NOT NULL,
    NOTA_RUIDO            NUMBER(1),
    NOTA_LUZ              NUMBER(1),
    NOTA_ESTIMULO_VISUAL  NUMBER(1),
    COMENTARIO            VARCHAR2(500),
    DATA_AVALIACAO        DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_AVALIACAO_ESTACAO PRIMARY KEY (ID_AVALIACAO),
    CONSTRAINT FK_AVALIACAO_RESERVA FOREIGN KEY (ID_RESERVA)
        REFERENCES RESERVA_ESTACAO (ID_RESERVA),
    CONSTRAINT CK_AVALIACAO_NOTA_GERAL CHECK (NOTA_CONFORTO_GERAL BETWEEN 1 AND 5),
    CONSTRAINT CK_AVALIACAO_NOTA_RUIDO CHECK (NOTA_RUIDO BETWEEN 1 AND 5),
    CONSTRAINT CK_AVALIACAO_NOTA_LUZ CHECK (NOTA_LUZ BETWEEN 1 AND 5),
    CONSTRAINT CK_AVALIACAO_NOTA_VISUAL CHECK (NOTA_ESTIMULO_VISUAL BETWEEN 1 AND 5)
);

